source 'https://rubygems.org'
ruby "2.1.2"
gem 'rails', '4.2.0.beta2'
gem 'rails-api'
gem 'pg'
gem 'rack-cors'
gem 'bcrypt-ruby', '~> 3.1.2'
gem 'active_model_serializers', github: 'rails-api/active_model_serializers'
gem 'rack-ssl-enforcer'

group :development, :test do
  gem 'rspec-rails', '~> 3.0'
  gem 'spring'
  gem 'pry-rails'
end

group :production do
  gem 'unicorn'
end


